!!python/object:options.Options
feature_volume_type: mlp_feature_volume
batch_size: 12
cost_volume_aggregation: dot
cv_encoder_type: multi_scale_encoder
depth_decoder_name: unet_pp
gpus: 2
image_encoder_name: efficientnet
log_interval: 100
loss_type: log_l1
lr: 0.0001
wd: 0.0001
matching_encoder_type: resnet
name: implicit_depth_temporal
num_sanity_val_steps: 0
num_workers: 12
precision: 16
random_seed: 0
full_depth_supervision: true
lr_steps: [18000, 36000]
max_steps: 14000
lazy_load_weights_from_checkpoint: weights/implicit_depth.ckpt
near_surface_ratio: 0.25
bd_regularisation_weight: 0.5
binary_loss_positive_weight: 1.0
bd_edge_regularision: true
use_prior: true